# Mount code for hot reloading and cache for faster compile in dev mode.
version: '3.1'

services:

  helloworld:
    build: .
    volumes:
      - ./server:/usr/src/server
      - ./sbt_cache/coursier:/root/.cache/coursier
      - ~/.sbt:/root/.sbt
      - ~/.ivy:/root/.ivy2
      - ~/.m2:/root/.m2
