AWSTemplateFormatVersion: '2010-09-09'
Description: 'The DB password and application secret key - randomly generated server side and not accessible.'
Parameters:
  Environment:
    Type: String
    AllowedValues: ["staging", "prod"]
    Description: "Staging or prod environment"
Resources:
  password:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join ["-", [!Ref Environment, "databasepassword"]]
      Description: "This is the password for the database, shared with the container."
      GenerateSecretString:
        PasswordLength: 40
        ExcludeCharacters: '"@/\'
  secretkey:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join ["-", [!Ref Environment, "secretkey"]]
      Description: "This is the secret key for the application."
      GenerateSecretString:
        PasswordLength: 40
Outputs:
  Key:
    Description: The secret key for the application
    Value: !Ref secretkey
    Export:
      Name: !Sub '${AWS::StackName}-key'
  Password:
    Description: The password for the database
    Value: !Ref password
    Export:
      Name: !Sub '${AWS::StackName}-pwd'
